[E] Extend Functionality
mmatongo/chew pull request #23
Opened 2024-09-04 20:05 UTC by mmatongo

closes #20

2024-09-05 14:28 UTC, mmatongo commented
@ccoVeille thoughts? there's a bit of gibberish in there

2024-09-07 20:24 UTC, ccoVeille requested changes

2024-09-07 20:24 UTC, ccoVeille commented on chew.go
> +	}
What about this


```suggestion
	client := httpClient
	if client == nil {
		transport := http.DefaultTransport
		if proxyURL := getNextProxy(); proxyURL != nil {
			transport = &http.Transport{
				Proxy: http.ProxyURL(proxyURL),
			}
		}
		client = &http.Client{
			Timeout:   30 * time.Second,
			Transport: transport,
		}
	}
```

2024-09-07 20:24 UTC, ccoVeille commented on chew.go
> +	"golang.org/x/time/rate"
Usually external libraries are added in a dedicated section


```suggestion
 	"context"
 	"fmt"
 	"io"
 	"net/http"
	"net/url"
 	"strings"
 	"sync"
	"time"

	"github.com/temoto/robotstxt"
	"golang.org/x/time/rate"
 
 	"github.com/mmatongo/chew/v1/internal/common"
 	"github.com/mmatongo/chew/v1/internal/document"
 	"github.com/mmatongo/chew/v1/internal/text"
 	"github.com/mmatongo/chew/v1/internal/transcribe"
 	"github.com/mmatongo/chew/v1/internal/utils"
```

2024-09-07 20:24 UTC, ccoVeille commented on chew.go
> +	userAgent         = "Chew/1.0 (+https://github.com/mmatongo/chew)"
This one could be a constant

2024-09-07 20:24 UTC, ccoVeille commented on chew.go
> +}
I'm not fan of these:
- having a init
- having package variables

It could lead to race issues

I will try to develop if you are interested, but it would require a refactoring of the code in this PR

2024-09-07 20:24 UTC, ccoVeille commented on chew.go
> +	return allowed, crawlDelay, nil
I would remove the allowed from signature, and return an error when not allowed

2024-09-07 20:24 UTC, ccoVeille commented on chew.go
> +					if err := respectCrawlDelay(url, crawlDelay); err != nil {
You should pass the context as first argument

So you can cancel the time.Sleep when the context expires

2024-09-07 20:24 UTC, ccoVeille commented on chew.go
>  	ctx := context.Background()
You should pass the context the first argument of the function

2024-09-07 20:24 UTC, ccoVeille commented on chew.go
> +to use for transcription, a potion to enable diarization including the min and max speakers and
maybe something to explain what is diarization

```suggestion
to use for transcription, a potion to enable diarization (blah blah...) including the min and max speakers and
```

2024-09-07 20:24 UTC, ccoVeille commented on chew.go
>  	ctx := context.Background()
But I'm noticing you have a big issue with the way you handle your context

it should be addressed, but not necessarily in this PR

2024-09-07 20:24 UTC, ccoVeille commented on chew.go
> +		}
a time.Sleep is blocking

if you have a context that expires (when the app dies for example), the sleep cannot be cancelled

I would like to suggest you adding a function to sleep

```go
func Wait(ctx, d time.Duration) {
      select {
          case <-time.After(d):         
          case <-ctx.Done():
}
````

This way you don't wait when the context is expired

2024-09-07 20:24 UTC, ccoVeille commented on chew.go
> +func processWithRetry(url string, ctx context.Context) ([]common.Chunk, error) {
```suggestion
func processWithRetry(ctx context.Context, url string) ([]common.Chunk, error) {
```

the context is by convention always the first argument, the same way the error is always the last one

2024-09-07 20:24 UTC, ccoVeille commented on chew.go
>  func processURL(url string, ctxs ...context.Context) ([]common.Chunk, error) {
it's an internal function, you should refactor it

ctxs as a variadic is not a good thing

You should have this

```suggestion
func processURL(ctx context.Context, url string) ([]common.Chunk, error) {
```

2024-09-07 20:24 UTC, ccoVeille commented on chew.go
> +			return true, crawlDelay, nil
returning a crawl delay via this function while  crawlDelay is a global variable is a bad idea

I mean this function don't handle/alter the crawlDelay, you should simply use it where you call this function

2024-09-07 20:24 UTC, ccoVeille commented on chew.go
> +			time.Sleep(retryDelay)
same remark as before this time.Sleep should check the context

2024-09-07 20:24 UTC, ccoVeille commented on chew.go
> +}
This should be something that is not at package level, but a method of an object

Your NewConfig object is a good idea, but you should have a Chew instance returned, then SettHTTPClient can be used on it

All your existing methods should be replaced to me method of the object

Then if you want to keep a retro compatibility, you should create a defaultChew = NewChewig(common.Config{})

then you rewrite existing exported method to call the defaultChew

```go
func Process(urls []string, ctxs ...context.Context) ([]common.Chunk, error) {
	ctx := context.Background()
	if len(ctxs) > 0 {
		ctx = ctxs[0]
	}
	return defaultChew.Process(ctx, urls)
}
```

2024-09-07 20:24 UTC, ccoVeille commented on chew.go
>  func Process(urls []string, ctxs ...context.Context) ([]common.Chunk, error) {
it's too later but ctx should always be the first argument, here you used a variadic trick to solve the issues, but it's a bit dirty, especially if you consider the variadic can be used to pass more than one context, and your code will silently only use the first one

If it's not too late, I would change the signature

2024-09-07 20:24 UTC, ccoVeille commented on chew.go
>  func Process(urls []string, ctxs ...context.Context) ([]common.Chunk, error) {
The number of your stars, and the fact there is no public project using chew for now, means it's not too late

https://pkg.go.dev/github.com/mmatongo/chew
> Imported by: 0

2024-09-08 09:44 UTC, mmatongo commented on chew.go
>  	ctx := context.Background()
I think I see what you mean

2024-09-08 09:45 UTC, mmatongo commented on chew.go
>  func processURL(url string, ctxs ...context.Context) ([]common.Chunk, error) {
I didn't actually know that this was the case, initially I made it like this so that the context itself would be optional

2024-09-08 09:47 UTC, mmatongo commented
@ccoVeille let me address the issues raised and request another review, thank you for the insight. I really appreciate it

2024-09-08 10:54 UTC, ccoVeille commented
Sure! Good luck and have fun! 😁

2024-09-15 19:31 UTC, ccoVeille commented on chew.go
> +and files and returns the content of the URLs and files as a list of Chunks. It also provides a way to
```suggestion
and files, and returns the content of the URLs and files as a list of Chunks. It also provides a way to
```

2024-09-15 19:31 UTC, ccoVeille commented on chew.go
> +  - When scraping websites, ensure compliance with the target website's terms of service and robots.txt rules.
You should add something about the fact even if the library tries to respect the robots.txt file, the user is responsible.

Or something like that

2024-09-15 19:31 UTC, ccoVeille commented on chew.go
> +and files and returns the content of the URLs and files as a list of Chunks. It also provides a way to
```suggestion
and files and returns the content of the URLs and files as a list of chunks. It also provides a way to
```

2024-09-15 19:31 UTC, ccoVeille commented on chew.go
> +The library respects robots.txt files and crawl delays, and allows you to set a custom http.Client for making requests.
```suggestion
The library respects rules defined in robots.txt file and crawl delays, and allows you to set a custom http.Client for making requests.
```

There is only one robots.txt file unless I'm wrong

2024-09-15 19:31 UTC, ccoVeille commented on chew.go
> +	"golang.org/x/time/rate"
You didn't work on this

2024-09-15 19:31 UTC, ccoVeille commented on chew.go
> +to use for transcription, a potion to enable diarization (the process of separating and labeling
Is potion the right word?

2024-09-15 19:31 UTC, ccoVeille commented on chew.go
> +an option to clean up the audio file from GCS after transcription is complete.
Please write something like this


```suggestion
an option to clean up the audio file from Google Cloud Speech-to-Text (GCS) after transcription is complete.
```

2024-09-15 19:31 UTC, ccoVeille commented on chew.go
> +			}
Here is a simpler way.

```suggestion
			select {
			case <-timer.After(timeToWait):
			case <-ctx.Done():
				return ctx.Err()
			}
```

2024-09-15 19:31 UTC, ccoVeille commented on chew.go
> +			}
If you don't use my suggestion of using time.After 

Then you should consider using defer timer.Stop


```suggestion
			timer := time.NewTimer(timeToWait)
			defer timer.Stop()
			select {
			case <-timer.C:
			case <-ctx.Done():
				return ctx.Err()
			}
```

2024-09-15 19:31 UTC, ccoVeille commented on chew.go
> +	return nil, err
```suggestion
	var retries int
	for {
		chunks, err = c.processURL(ctx, url)
		if err == nil {
			return chunks, nil
		}

		if retries > c.config.RetryLimit {
			break
		}
		retries++
		c.wait(ctx, c.config.RetryDelay)
	}

	return nil, err
```

2024-09-16 07:43 UTC, mmatongo commented on chew.go
> +  - When scraping websites, ensure compliance with the target website's terms of service and robots.txt rules.
Okay

2024-09-16 07:46 UTC, mmatongo commented on chew.go
> +to use for transcription, a potion to enable diarization (the process of separating and labeling
Nope, should be an option

2024-09-16 07:46 UTC, mmatongo commented on chew.go
> +an option to clean up the audio file from GCS after transcription is complete.
done

2024-09-16 08:01 UTC, mmatongo commented on chew.go
> +			}
I used your earlier suggestion and it exposed a race condition. Thanks!!!

2024-09-16 11:15 UTC, ccoVeille commented on chew.go
> +to use for transcription, a potion to enable diarization (the process of separating and labeling
Haha 😂

2024-09-16 11:16 UTC, ccoVeille commented on chew.go
> +			}
Great then

2024-09-16 15:12 UTC, merged